import gtfsToHtml from "gtfs-to-html";
import { join } from "node:path";

const gtfs = await Array.fromAsync(new Bun.Glob("**/*.zip").scan("gtfs"));
console.log(gtfs);

await gtfsToHtml({
  agencies: gtfs.map((gtf) => ({
    agencyKey: gtf.replace(/\.zip$/, ""),
    path: join("gtfs", gtf),
  })),
  allowEmptyTimetables: false,
  beautify: false,
  coordinatePrecision: 5,
  dateFormat: "MMM D, YYYY",
  daysShortStrings: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  daysStrings: [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
  ],
  defaultOrientation: "vertical",
  interpolatedStopSymbol: "•",
  interpolatedStopText: "Estimated time of arrival",
  linkStopUrls: false,
  mapStyleUrl: "https://tiles.openfreemap.org/styles/liberty",
  menuType: "jump",
  noDropoffSymbol: "‡",
  noDropoffText: "No drop off available",
  noHead: false,
  noPickupSymbol: "**",
  noPickupText: "No pickup available",
  noServiceSymbol: "—",
  noServiceText: "No service at this stop",
  outputFormat: "html",
  overwriteExistingFiles: true,
  outputPath: "custom/output/path",
  requestDropoffSymbol: "†",
  requestDropoffText: "Must request drop off",
  requestPickupSymbol: "***",
  requestPickupText: "Request stop - call for pickup",
  serviceNotProvidedOnText: "Service not provided on",
  serviceProvidedOnText: "Service provided on",
  showArrivalOnDifference: 0.2,
  showCalendarExceptions: true,
  showDuplicateTrips: false,
  showMap: true,
  showOnlyTimepoint: true,
  showRouteTitle: true,
  showStopCity: true,
  showStopDescription: true,
  showStoptimesForRequestStops: true,
  skipImport: false,
  sortingAlgorithm: "common",
  timeFormat: "h:mma",
  useParentStation: true,
  verbose: true,
  zipOutput: false,
});
