name: Update View for GTFS Data

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-view:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: "24"
      - uses: actions/setup-go@v5

      - run: |
          bun install

          cd gtfs-view
          bun install

          go install github.com/public-transport/gtfsclean@latest

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Checkout gtfs branch
        run: |
          rm -rf gtfs-branch

          git clone --branch gtfs --single-branch https://github.com/${{ github.repository }}.git gtfs-branch

      - name: Copy and commit GTFS files
        run: |
          cp -r gtfs-branch/gtfs gtfs
          NODE_OPTIONS=--max_old_space_size=8000 node gtfs-view/index.mjs

          cd gtfs-branch

          rm -rf view || true
          mkdir -p view

          cp -r ../.tmp/build/gtfs-view/* view/

          git add -A
          git commit -m "👀 Update View for GTFS data $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gtfs
